name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main  # Runs on push to main branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

      - name: Build and tag multi-architecture Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/hello-world:latest --push .

      - name: Push Docker image to ACR
        run: |
          # This step is not necessary anymore because we already used the `--push` flag in the build step
          echo "Image has been pushed to ACR"
